INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);
INSERT INTO users (name,age) VALUES ('Marcus', 12);

INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);
INSERT INTO projects (title,category,funding_goal,start_date,end_date) VALUES ('Title','Charity',150,3,5);

INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
INSERT INTO pledges (amount,user_id,project_id) VALUES (10,'Charity','Double_charity');
