INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);
INSERT INTO users (name, age) VALUES ('briana', 20);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Awesome', 'Awesomeness', '1000', '10/10/2018', '10/10/2019');

INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 'rogerman', 'Awesome');
