INSERT INTO users (name, age) VALUES ("Dre", 6);
INSERT INTO users (name, age) VALUES ("Ana", 423);
INSERT INTO users (name, age) VALUES ("Tania", 642);
INSERT INTO users (name, age) VALUES ("Josh", 62);
INSERT INTO users (name, age) VALUES ("John", 23);
INSERT INTO users (name, age) VALUES ("Drew", 31);
INSERT INTO users (name, age) VALUES ("Drewia", 31);
INSERT INTO users (name, age) VALUES ("Joesph", 6);
INSERT INTO users (name, age) VALUES ("Kevin", 23);
INSERT INTO users (name, age) VALUES ("Briana", 6);
INSERT INTO users (name, age) VALUES ("Nemanja", 24);
INSERT INTO users (name, age) VALUES ("Lindsey", 6);
INSERT INTO users (name, age) VALUES ("Mo", 12);
INSERT INTO users (name, age) VALUES ("Julian", 6);
INSERT INTO users (name, age) VALUES ("Kenny", 21);
INSERT INTO users (name, age) VALUES ("Johann", 6);
INSERT INTO users (name, age) VALUES ("Daniel", 7);
INSERT INTO users (name, age) VALUES ("Terrence", 6);
INSERT INTO users (name, age) VALUES ("Dre", 9);
INSERT INTO users (name, age) VALUES ("Dre", 10);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("objects", "ruby", 100, 2017-01-01, 2018-01-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("variables", "ruby", 200, 2017-06-01, 2018-06-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("I'm sleepy", "sleep study", 1000, 2017-04-01, 2018-05-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("tables", "SQL", 5, 2017-01-20, 2017-08-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("house", "project", 10000, 2017-08-01, 2019-01-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("soccer", "team", 1, 2017-04-05, 2017-09-08);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("pizza", "food", 100000, 2017-12-19, 2017-12-20);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project pizza", "restaurant", 500, 2017-04-19, 2017-07-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("no salads", "food", -100, 2017-02-01, 2018-01-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("shoes", "project", 110, 2017-01-01, 2018-01-01);

INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 1, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (43.50, 2, 29);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.60, 3, 28);
INSERT INTO pledges (amount, user_id, project_id) VALUES (74.50, 4, 27);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.55, 5, 26);
INSERT INTO pledges (amount, user_id, project_id) VALUES (38.50, 6, 25);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 7, 24);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 8, 23);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 9, 22);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 10, 21);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 11, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 12, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 13, 18);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 14, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 15, 16);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 16, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 17, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 18, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 19, 12);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 20, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 21, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 22, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 23, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 24, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 25, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 26, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 27, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 28, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 29, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (34.50, 30, 1);
